name: Release Drafter

on:
  push:
    branches:
    - $default-branch
    - release-*

jobs:
  update_release_draft:
    runs-on: ubuntu-18.04
    steps:
      # Drafts your next Release notes as Pull Requests are merged
      # https://github.com/raboof/release-drafter/releases
      # fork of https://github.com/release-drafter/release-drafter/releases
      - uses: raboof/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
